plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/tmp/**/*'
    - 'tmp/**/*'
    - 'lib/rls_multi_tenant/generators/**/templates/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 130

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'
    - 'lib/rls_multi_tenant/generators/**/*'

Metrics/MethodLength:
  Max: 25

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false